version: "3.9"

services:
  eda_preprocessing:
    build:
      context: .  # Définit le contexte comme le répertoire racine
      dockerfile: ./eda_preprocessing/Dockerfile
    container_name: eda_preprocessing_container
    volumes:
      - ./data:/app/data  # Montez un dossier si nécessaire

  modeling:
    build:
      context: .  # Définit le contexte comme le répertoire racine
      dockerfile: ./modeling/Dockerfile
    container_name: modeling_container
    volumes:
      - ./data:/app/data  # Montez un dossier si nécessaire
