name: Deploy Documentation

on:
  push:
    branches:
      - main  # Déclencher uniquement sur la branche "main"

permissions:
  contents: write  # Donne accès en écriture pour le contenu du dépôt

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Cloner le dépôt
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Installer Python et MkDocs
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install MkDocs and dependencies
        run: pip install mkdocs mkdocs-material

      # Étape 3 : Construire le site avec MkDocs
      - name: Build MkDocs site
        run: mkdocs build

      # Étape 4 : Copier les fichiers générés dans la racine du dépôt
      - name: Move files to root
        run: |
          cp -r site/* .
          rm -rf site

      # Étape 5 : Commit et push des fichiers générés
      - name: Commit and Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "MehdiNemri"
          git config user.email "MehdiNemri@github.com"
          git add .
          git commit -m "Update documentation" || echo "No changes to commit"
          git push origin main

