name: Create Release
on:
  push:
    tags:
      - 'v*'
permissions:
  contents: write
jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # This ensures we fetch all history for changelog generation

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: python3 -m pytest tests

      - name: Generate changelog
        id: changelog
        run: |
          # Get the previous tag, fallback to first commit if no previous tag exists
          PREVIOUS_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || git rev-list --max-parents=0 HEAD)
          CURRENT_TAG=${GITHUB_REF#refs/tags/}
          
          # Generate changelog with error handling
          echo "# Changelog for $CURRENT_TAG" > changelog.txt
          echo "" >> changelog.txt
          echo "## Changes:" >> changelog.txt
          git log --no-merges --pretty=format:"* %h - %s (%an)" $PREVIOUS_TAG..HEAD >> changelog.txt
          
          # Verify changelog is not empty
          if [ ! -s changelog.txt ]; then
            echo "No changes found between tags. Adding default message."
            echo "* No changes recorded in this release" >> changelog.txt
          fi
          
          # Make changelog available as output
          changelog=$(cat changelog.txt)
          echo "changelog<<EOF" >> $GITHUB_OUTPUT
          echo "$changelog" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./changelog.txt
          body_path: ./changelog.txt
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: false
